"""cria tabela configuracoes

Revision ID: 2f550cc9cdb5
Revises: 0c93945949fc
Create Date: 2026-08-13 04:41:20.483796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f550cc9cdb5'
down_revision: Union[str, Sequence[str], None] = '0c93945949fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_empresa', sa.String(length=150), nullable=False),
    sa.Column('nome_sistema', sa.String(length=150), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('cor_primaria', sa.String(length=20), nullable=False),
    sa.Column('cor_secundaria', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
