"""criar tabela relatorios apartamentos

Revision ID: 3c3522e8be9e
Revises: dc6af66a3ddd
Create Date: 2026-08-11 12:57:09.201640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3522e8be9e'
down_revision: Union[str, Sequence[str], None] = 'dc6af66a3ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('bloco', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DISPONIVEL', 'RESERVADO', 'OCUPADO', 'MANUTENCAO', name='statusapartamento'), nullable=False),
    sa.Column('proprietarioId', sa.Uuid(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criadoEm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizadoEm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorios_apartamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('apartamento_id', sa.Uuid(), nullable=False),
    sa.Column('mes', sa.String(length=20), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('receita_bruta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('internet', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('copel', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('condominio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('limpeza', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reparos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('administracao', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('custos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('receita_liquida', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ocupacao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valor_ap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('locacao_normal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('renda_passiva', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rentabilidade', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('media_mercado', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartamento_id'], ['apartamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatorios_apartamentos')
    op.drop_table('apartamentos')
    # ### end Alembic commands ###
