"""criar tabela visitas

Revision ID: 711e47b1eaf4
Revises: b79b365148af
Create Date: 2026-08-13 03:33:30.926574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711e47b1eaf4'
down_revision: Union[str, Sequence[str], None] = 'b79b365148af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('apartamento_id', sa.Uuid(), nullable=False),
    sa.Column('contato_id', sa.Uuid(), nullable=False),
    sa.Column('corretor_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_status', sa.String(length=30), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartamento_id'], ['apartamentos.id'], ),
    sa.ForeignKeyConstraint(['contato_id'], ['contatos.id'], ),
    sa.ForeignKeyConstraint(['corretor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitas')
    # ### end Alembic commands ###
