"""adiciona unicidade na competencia do relatorio

Revision ID: 733e4d5491aa
Revises: ab7b28165851
Create Date: 2026-08-12 16:51:25.193367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733e4d5491aa'
down_revision: Union[str, Sequence[str], None] = 'ab7b28165851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_relatorio_apartamento_competencia', 'relatorios_apartamentos', ['apartamento_id', 'mes', 'ano'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_relatorio_apartamento_competencia', 'relatorios_apartamentos', type_='unique')
    # ### end Alembic commands ###
