"""criar tabelas de conversas e mensagens

Revision ID: c636c0be16a8
Revises: 3c3522e8be9e
Create Date: 2026-08-11 20:15:23.018728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c636c0be16a8'
down_revision: Union[str, Sequence[str], None] = '3c3522e8be9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.Column('ultima_mensagem', sa.String(length=1000), nullable=True),
    sa.Column('horario', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nao_lidas', sa.Integer(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversas_id'), 'conversas', ['id'], unique=False)
    op.create_index(op.f('ix_conversas_telefone'), 'conversas', ['telefone'], unique=False)
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('arquivo_url', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('horario', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_conversa_id'), 'mensagens', ['conversa_id'], unique=False)
    op.create_index(op.f('ix_mensagens_id'), 'mensagens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_id'), table_name='mensagens')
    op.drop_index(op.f('ix_mensagens_conversa_id'), table_name='mensagens')
    op.drop_table('mensagens')
    op.drop_index(op.f('ix_conversas_telefone'), table_name='conversas')
    op.drop_index(op.f('ix_conversas_id'), table_name='conversas')
    op.drop_table('conversas')
    # ### end Alembic commands ###
