"""criar tabela usuarios

Revision ID: dc6af66a3ddd
Revises: 7e06afeb1e54
Create Date: 2026-08-11 07:08:33.136327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6af66a3ddd'
down_revision: Union[str, Sequence[str], None] = '7e06afeb1e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senhaHash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('ADMINISTRADOR', 'CORRETOR', 'ATENDENTE', name='tipousuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criadoEm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizadoEm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
