"""cria integracao google calendar

Revision ID: e668c81633f7
Revises: 2f550cc9cdb5
Create Date: 2026-08-13 14:11:04.206464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e668c81633f7'
down_revision: Union[str, Sequence[str], None] = '2f550cc9cdb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('configuracao_id', sa.UUID(), nullable=False),
    sa.Column('email_google', sa.String(length=150), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('conectado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['configuracao_id'], ['configuracoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('configuracao_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_calendar_integrations')
    # ### end Alembic commands ###
