"""adicionar direcao e whatsapp message id

Revision ID: f6b6153ddfdf
Revises: c636c0be16a8
Create Date: 2026-08-11 20:38:34.421047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b6153ddfdf'
down_revision: Union[str, Sequence[str], None] = 'c636c0be16a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensagens', sa.Column('direcao', sa.String(length=20), nullable=False))
    op.add_column('mensagens', sa.Column('whatsapp_message_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_mensagens_whatsapp_message_id'), 'mensagens', ['whatsapp_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_whatsapp_message_id'), table_name='mensagens')
    op.drop_column('mensagens', 'whatsapp_message_id')
    op.drop_column('mensagens', 'direcao')
    # ### end Alembic commands ###
